name = "SphericoMC"
author = "Spherico Hub Contributors"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "130c2e9faffe800fa292999e3f39f3b636c417e82c66040dbc39699505541740"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
