name = "SphericoMC"
author = "Spherico Hub Contributors"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d19badb7bf85be5d0c883b7719bece92763d52886a6ae730f74806610114f9ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
