version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
mcwfences = true
mutantmonsters = true
mcwroofs = true
barteringstation = true
mcwwindows = true
createpropulsion = true
crowns = true
chimes = true
easymagic = true
numismatics = true
mcwstairs = true
cataclysm = true
easyanvils = true
copycats = true
irons_spellbooks = true
ctl = true
diagonalwalls = true
createdieselgenerators = true
chalk = true
aeroclaims = true
create_submarine = true
mcwlights = true
mcwtrpdoors = true
mcwbridges = true
escalated = true
railways = true
bellsandwhistles = true
bits_n_bobs = true
amendments = true
handcrafted = true
electroenergetics = true
diagonalfences = true
snowrealmagic = true
moonlight = true
rechiseledcreate = true
advancednetherite = true
dawnoftimebuilder = true
eternalnether = true
morevillagers = true
exposure = true
offroad = true
mcwdoors = true
chiselsandbits = true
floralench = true
dynamictreesplus = true
supplementaries = true
apotheosis = true
deeperdarker = true
chipped = true
createrailwaysnavigator = true
doggytalents = true
create = true
aeronautics = true
dynamictrees = true
buildinggadgets2 = true
simulated = true
sereneseasons = true
visualworkbench = true
minecraft = true
enderzoology = true
mcwfurnitures = true
irons_lib = true
createdeco = true
create_wizardry = true
betterarcheology = true
travelersbackpack = true
createaddition = true
apothic_enchanting = true
dragonlib = true
additional_lights = true
createframed = true
dtterralith = true
irons_patreon_lib = true
diagonalwindows = true
create_bb = true
analogaudio = true
fishermans_haven = true
illagerinvasion = true
rechiseled = true
create_power_loader = true
